input: touchscreen/fingerprint: Fix symbol conflicts with namespaces
Both laurel and ginkgo have customized versions of the same driver, but
for each device, which obviously causes symbol conflicts when compiled
together.

ld.lld: error: duplicate symbol: fts_create_apk_debug_channel
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_ex_fun.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_ex_fun.o)

ld.lld: error: duplicate symbol: fts_read_file
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_flash.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_flash.o)

ld.lld: error: duplicate symbol: fts_upgrade_bin
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_flash.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_flash.o)

ld.lld: error: duplicate symbol: fts_enter_test_environment
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_flash.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_flash.o)

ld.lld: error: duplicate symbol: fts_fwupg_init
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_flash.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_flash.o)

ld.lld: error: duplicate symbol: fts_create_gesture_sysfs
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_gesture.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_gesture.o)

ld.lld: error: duplicate symbol: fts_gesture_readdata
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_gesture.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_gesture.o)

ld.lld: error: duplicate symbol: fts_gesture_recovery
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_gesture.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_gesture.o)

ld.lld: error: duplicate symbol: fts_write
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_i2c.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_spi.o)

ld.lld: error: duplicate symbol: fts_write_reg
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_i2c.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_spi.o)

ld.lld: error: duplicate symbol: get_keyword_value
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_test/focaltech_test_ini.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_test/focaltech_test_ini.o)

ld.lld: error: duplicate symbol: fts_test_get_testparam_from_ini
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_test/focaltech_test_ini.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_test/focaltech_test_ini.o)

ld.lld: error: duplicate symbol: fts_release_apk_debug_channel
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_ex_fun.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_ex_fun.o)

ld.lld: error: duplicate symbol: fts_create_sysfs
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_ex_fun.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_ex_fun.o)

ld.lld: error: duplicate symbol: fts_gesture_suspend
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_gesture.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_gesture.o)

ld.lld: error: duplicate symbol: fts_remove_sysfs
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_ex_fun.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_ex_fun.o)

ld.lld: error: duplicate symbol: fts_ex_mode_recovery
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_ex_mode.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_ex_mode.o)

ld.lld: error: duplicate symbol: fts_wait_tp_to_valid
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_core.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_core.o)

ld.lld: error: duplicate symbol: fts_ex_mode_init
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_ex_mode.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_ex_mode.o)

ld.lld: error: duplicate symbol: fts_tp_state_recovery
>>> defined in built-in.o(drivers/input/touchscreen/focaltech_touch_f9s/focaltech_core.o)
>>> defined in built-in.o(drivers/input/touchscreen/ft8719_spi_c3j/focaltech_core.o)

ld.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)

Because it would be arduous work going in and replacing all of them manually,
we can simply include a header that prefixes them to their own namespace
so that they can all link into the same kernel binary.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>