memlat: Fix build error after function signature change
../drivers/devfreq/arm-memlat-mon.c:110:67: error: too few arguments to function call, expected 4, have 2
  110 |         if (!event->pevent || perf_event_read_local(event->pevent, &total))
      |                               ~~~~~~~~~~~~~~~~~~~~~                      ^
../include/linux/perf_event.h:924:5: note: 'perf_event_read_local' declared here
  924 | int perf_event_read_local(struct perf_event *event, u64 *value,
      |     ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  925 |                           u64 *enabled, u64 *running);
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Caused by 6e5e3fdc138f44839b8d016a71ef8a9fcea5c638 ("BACKPORT: bpf: perf event change needed for subsequent bpf helpers")

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>